curl -G "https://api.bilibili.com/x/web-interface/search/type" ^
--data-urlencode "search_type=video" ^
--data-urlencode "keyword=手机" ^
--data-urlencode "order=totalrank" ^
--data-urlencode "duration=0" ^
--data-urlencode "tids=0" ^
--data-urlencode "page=1" ^
-b "SESSDATA=03ddd569%2C1744078113%2Cdf907%2Aa1CjDQJNu1r_IxnkoWyyWbOh_YJIppEtAhKy1jzt5piKKecWggs2uNtvt-F-JJSBYX2LkSVjV2OXBidHFqZUxFVi1FNGJyZ1pzSHcxQlFEWXNWREpnYWFoZ2JLOHNwdG9GVjdsY19PR0JqSHRQUzhFY1hSaGppNUtOdjVHZ3JicXc1Q0w0c1ZEREl3IIEC"